### ISSUE TITLE
Add extra large (XL) support

### ISSUE THREAD

**Issue by meta-state** [ngengs/bootstrap-grid-flexbox#2]
col-flex-xl-

[https://getbootstrap.com/docs/4.0/layout/grid/#grid-options](url)
Extra Large ≥1200px
Max Container Width: 1140px

**Comment by ngengs** [comment]
I think its already support ≥1200px, `col-flex-lg` can handle that. And if you see in Bootstrap 4 `xl` breakpoint is same as `lg` breakpoint in Bootstrap 3.


FYI this style doesn't create container, you must create by your self, it only create the grid component.
